import hashlib,json,pathlib
root=pathlib.Path("/Users/n/numi-human-retained-delivery-20261009/skin-source-binding-1202")
screen=root/"counterfactual-screen-terminal-1201"
def sha(p): return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def read(p): return json.loads(pathlib.Path(p).read_text())
candidate=read(screen/"step-20000.result.json")
summary=read(screen/"summary.json")
decl=read(screen/"declaration.json")
baseline=read("/Users/n/numi-human-retained-delivery-20261009/native-flat-reference-40s-1201/skin-audit-1201-terminal/step-20000.result.json")
dir_report=read(root/"dirichlet/dirichlet-reconstruction-report.json")
builder=root/"build_dirichlet_candidate.py"
runner=root/"screen_dirichlet_terminal.py"
review={
 "schema":"numi.human.skin-dirichlet-terminal-counterfactual-review.v1",
 "status":"complete_counterfactual_screen_worse_than_flat_control",
 "qualification":"One terminal-pose offline counterfactual screen only; not an actual native candidate capture, not admission, not full-cycle clearance or physiology qualification.",
 "native_reference":{"run":"/Users/n/numi-human-retained-delivery-20261009/native-flat-reference-40s-1201/native-run","accepted_step":20000,"accepted_time_s":40.00000189989805,"accepted_pack_sha256":decl["native_reference"]["pack_sha256"],"accepted_receipt_sha256":decl["native_reference"]["receipt_sha256"],"native_NHA_sha256":decl["native_reference"]["NHA_sha256"],"baseline_skin_sha256":decl["native_reference"]["original_skin_sha256"],"baseline_audit_result_sha256":"9703c87b6e0fcb2e8a7fc0b8f25eaf8124659d3db0712f4b9a5f83a9cad1ede6"},
 "candidate":{"path":"/Users/n/numi-human-retained-delivery-20261009/skin-source-binding-1202/counterfactual-screen-input/candidate-dirichlet.nhskin","sha256":"f7c8fdb1990bed9ab1fe8355bfc432043d268bec1b858e379d7f893ff51567df","build_report_sha256":sha(root/"counterfactual-screen-input/candidate-build-report.json"),"weight_solution_npz_sha256":"8ee440a0e346ba253c32cf693661b889c622908cd7355c13ef50ae1d9187aae8","weight_solution_report_sha256":"a979ed813e20544f4f0b9e9e03784d652abb5440dd60939107c360e5ca978803","independent_source_verifier_passed":True,"changed_weight_rows":dir_report["checks"]["vs_current_1187_full_weight_delta"]["changed_rows"],"max_abs_weight_delta":dir_report["checks"]["vs_current_1187_full_weight_delta"]["max_abs_weight_delta"],"candidate_payload_changes_only":["ABI5 full F32 weight matrix","per-vertex top-four diagnostic influence indices and weights"],"byte_identical":["NHSKIN header","86 binding records","all position and normal slots","triangle index bytes"]},
 "counterfactual_method":{"transform_owner":"/Users/n/numi-human-resting-evidence-20261005/native-vastus-lateralis-weight-row-erratum-1182/reproduce.py","transform_owner_sha256":sha("/Users/n/numi-human-resting-evidence-20261005/native-vastus-lateralis-weight-row-erratum-1182/reproduce.py"),"rule":"capture_skin_F32 + (candidate full-weight LBS - baseline full-weight LBS) at accepted body transforms; add that delta to captured coordinates, preserving captured common-field/respiratory residual","matrix_accumulation":"1182 Python transform owner uses double arithmetic; candidate result materialized once as F32","baseline_reconstruction_residual":decl["baseline_reconstruction_residual"],"candidate_LBS_delta":decl["candidate_LBS_delta"],"limitation":"Not the native runtime skinning result under changed weights. The new torso weighting can also change the shared thorax anchor/respiratory field; this screen holds that field and every target fixed."},
 "exact_terminal_audit":{"predicate":"exact_float32_lattice_triangle_intersection","target_surfaces":candidate["surface_target_count"],"contact_exemptions":[],"baseline":{"skin_target_pairs":baseline["all_skin_crossing_pair_count"],"nonocular_pairs":baseline["nonocular_crossing_pair_count"],"ocular_pairs":baseline["ocular_crossing_pair_count"],"skin_self_pairs":baseline["skin_self_crossing_pair_count"],"degenerate_skin_faces":len(baseline["skin_degenerate_face_rows"]),"invalid_target_triangles":baseline["invalid_target_triangle_count"]},"counterfactual":{"skin_target_pairs":candidate["all_skin_crossing_pair_count"],"nonocular_pairs":candidate["nonocular_crossing_pair_count"],"ocular_pairs":candidate["ocular_crossing_pair_count"],"skin_self_pairs":candidate["skin_self_crossing_pair_count"],"degenerate_skin_faces":len(candidate["skin_degenerate_face_rows"]),"invalid_target_triangles":candidate["invalid_target_triangle_count"]},"difference":{"added_skin_target_pairs":candidate["all_skin_crossing_pair_count"]-baseline["all_skin_crossing_pair_count"],"added_self_pairs":candidate["skin_self_crossing_pair_count"]-baseline["skin_self_crossing_pair_count"]},"coverage_complete":candidate["pair_coverage_complete"],"elapsed_s":candidate["elapsed_s"],"peak_rss_bytes":candidate["rss_peak_bytes"],"hit_surfaces":candidate["hit_surfaces"]},
 "input_hashes_unchanged":summary["input_hashes_unchanged"],
 "artifacts":{"candidate_build_script":{"path":str(builder),"sha256":sha(builder)},"screen_runner":{"path":str(runner),"sha256":sha(runner)},"screen_declaration":{"path":str(screen/"declaration.json"),"sha256":sha(screen/"declaration.json")},"screen_result":{"path":str(screen/"step-20000.result.json"),"sha256":sha(screen/"step-20000.result.json")},"screen_summary":{"path":str(screen/"summary.json"),"sha256":sha(screen/"summary.json")}}
}
p=screen/"screen-review.json"
p.write_text(json.dumps(review,indent=2,sort_keys=True,allow_nan=False)+"\n")
failed={"schema":"numi.human.skin-dirichlet-terminal-counterfactual.failed-attempt.v1","attempt":1,"screen_runner_sha256":"ea82c1c23c9bcbd57e3cb0a4451e12d41933ed1f0538d9a0539fd33c71631eb3","status":"preflight_failed_before_scan","error":"RuntimeError: captured NHSKIN vertex map is not a contiguous one-to-one source ordering","diagnosis":"Runner incorrectly required every source vertex to be referenced by a triangle. The receipt provides pack_first_vertex; source slots map contiguously from that offset, with some unused slots. Corrected by verifying every captured face index against pack_first_vertex + source NHSKIN face index and retaining all source slots for LBS delta.","native_pack_mutated":False,"candidate_mutated":False}
fp=screen/"failed-attempt-001.json"
fp.write_text(json.dumps(failed,indent=2,sort_keys=True)+"\n")
print(json.dumps({"review":str(p),"sha256":sha(p),"failure":str(fp),"failure_sha256":sha(fp),"status":review["status"],"baseline_pairs":baseline["all_skin_crossing_pair_count"],"candidate_pairs":candidate["all_skin_crossing_pair_count"],"candidate_self":candidate["skin_self_crossing_pair_count"],"difference":review["exact_terminal_audit"]["difference"]},sort_keys=True))
